Update mendeleydesktop to 1.13.8

diff --git a/mendeleydesktop/PKGBUILD b/mendeleydesktop/PKGBUILD
--- a/mendeleydesktop/PKGBUILD
+++ b/mendeleydesktop/PKGBUILD
@@ -1,64 +1,105 @@
-#
-# Part of chakra-project.org
-#
-# Maintainer: Francesco Marinucci <franzmari[at]chakra-project[dot]it>
-
 pkgname=mendeleydesktop
-pkgver=1.13.6
+pkgver=1.13.8
 pkgrel=1
 pkgdesc="Academic software for managing and sharing research papers (desktop client)"
 url=http://www.mendeley.com/release-notes/
 arch=('x86_64')
-depends=('python2' 'qt')
+depends=('python2' 'qtwebkit')
 license=('custom:mendeley_eula')
 install=mendeleydesktop.install
 categories=('education')
 screenshot=('http://www.timelordz.com/blog/wp-content/uploads/2010/08/MendeleyClient.png')
-source=("http://download.mendeley.com/linux/$pkgname-$pkgver-linux-x86_64.tar.bz2"
-        'mendeleydesktop.install')
-md5sums=('1c99b503897aeb3346cc0db89d053524'
-         '4f510b0f3e6369cd506cf9e4b3d4f9cd')
+source=("http://download.mendeley.com/linux/$pkgname-$pkgver-linux-x86_64.tar.bz2")
+sha512sums=('5a1546bda88c3c045a60b5f5884909736c8b3567f3d6fff1c9991d20558529f205f4207e364df925621257b34a382cbc073526c3229d789fcfac488a576c5fd5')
 
-package() {
-    cd "$pkgname-$pkgver-linux-x86_64"
+prepare() {
+    cd "${srcdir}/$pkgname-$pkgver-linux-x86_64"
 
-    rm -f share/doc/mendeleydesktop/*.txt
+    sed -i '1s@^#!/usr/bin/python$@&2@' bin/mendeleydesktop
+    
+    # remember, if you upgrade from 1.13.6 or older,
+    # remove any old versions of ".desktop" file of mendeley in ~/.local/share/applications/
+    # stop the creations of .desktop file of mendeley in ~/.local/share/applications/ 
+ echo   '#!/bin/sh
 
-    install -dm755 "$pkgdir/opt/$pkgname/"
-    mv bin lib share "$pkgdir/opt/$pkgname/"
-    #ln -s "../lib/mendeleydesktop/libexec/mendeleydesktop.x86_64" "$pkgdir/opt/$pkgname/bin/$pkgname"
-    cd "$pkgdir"
-    sed -i '1s@^#!/usr/bin/python$@&2@' opt/"$pkgname"/bin/mendeleydesktop
-    #install -Dm755 "bin/mendeleydesktop" "$pkgdir/usr/bin/mendeleydesktop"
-    install -dm755 "$pkgdir"/usr/bin
-    ln -s /opt/"$pkgname"/bin/mendeleydesktop "$pkgdir/usr/bin/mendeleydesktop"
+DESKTOP_PATH=$HOME/.local/share/applications/
+DESKTOP_FILE=$DESKTOP_PATH/mendeleydesktop.desktop
+MENDELEYDESKTOP_BIN=$HOME/.local/share/mendeleydesktop
+GCONF_TOOL=`which gconftool-2`
 
-    cd "$srcdir/$pkgname-$pkgver-linux-x86_64"
-    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
+if [ $? -ne 0 ]; then
+	echo "Unable to find gconftool-2.  The mendeley:// link handler may not be installed correctly." >&2
+fi
+if [ ! -d "$DESKTOP_PATH" ]; then
+	mkdir -p "$DESKTOP_PATH"
+fi
 
-    install -dm755 "$pkgdir"/usr/share/applications
-    ln -s /opt/"$pkgname"/share/applications/mendeleydesktop.desktop "$pkgdir"/usr/share/applications/
+while getopts "u" flag
+do
+	case $flag in
+	u)
+		# Uninstall the link handler
+		rm -f $DESKTOP_FILE
+		$GCONF_TOOL -u /desktop/gnome/url-handlers/mendeley
 
-    #Romove bundled Qt from package
-    cat << __EOF__
-Removing bundled Qt library.
-If you used "--force-bundled-qt" to start mendeley,
-make sure you remove any old versions of ".desktop" file of mendeley in ~/.local/share/applications/,
-because mendeley will automatically create one there.
-__EOF__
-    rm -rf "$pkgdir"/opt/"$pkgname"/lib/qt
+		exit 0
+		;;
+	\?)
+		echo "Unknown option: -$OPTARG" >&2
+		;;
+  	esac
+done
+
+shift $(($OPTIND - 1))
+if [ $# -ne 1 ]; then
+	echo "Usage: "`basename $0`" [options] <path>"
+	echo " -u : Uninstall the mendeley:// link handler"
+	echo ""
+	echo "Install the mendeley:// link handler to launch <path>"
+	echo ""
+	exit 1
+fi
+
+if [ ! -f "$1" ]; then
+	echo "Mendeley Desktop binary '$1' does not exist"
+	exit 1
+fi
+
+# install the gnome link handler
+$GCONF_TOOL -s /desktop/gnome/url-handlers/mendeley/command "$MENDELEYDESKTOP_BIN %s" --type String
+$GCONF_TOOL -s /desktop/gnome/url-handlers/mendeley/enabled --type Boolean true' > bin/install-mendeley-link-handler.sh
 
     #Remove unneeded lines if gconf is not installed.
     if ! which gconftool-2 &>/dev/null;then
     sed -i '6d;74d;75d' \
-        "$pkgdir"/opt/"$pkgname"/bin/install-mendeley-link-handler.sh
+        bin/install-mendeley-link-handler.sh
     fi
-    #force mendeley to use bundled qt because which under qt 4.8 crashes at start point
-    #make sure you remove any old versions of ".desktop" file of mendeley in ~/.local/share/applications/
-#    sed -i 's/^Exec.*$/& --force-bundled-qt/' "$pkgdir"/opt/"$pkgname"/share/applications/mendeleydesktop.desktop
-    for size in 16 22 32 48 64 128;do
-        install -dm755 "$pkgdir"/usr/share/icons/hicolor/${size}x${size}/apps
-        ln -s /opt/"$pkgname"/share/icons/hicolor/${size}x${size}/apps/"${pkgname}".png \
-          "$pkgdir"/usr/share/icons/hicolor/${size}x${size}/apps
-    done
+
+}
+
+package() {
+    cd "$pkgname-$pkgver-linux-x86_64"
+    
+    install -d ${pkgdir}/usr/{bin,lib,share}
+    
+    cp -R bin ${pkgdir}/usr
+    
+    # remove bundled Qt from package
+    rm -rf lib/qt
+    cp -R lib ${pkgdir}/usr
+    
+    install -D share/applications/${pkgname}.desktop ${pkgdir}/usr/share/applications/${pkgname}.desktop
+    install -D share/doc/${pkgname}/License.txt ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
+    
+    install -d ${pkgdir}/usr/share/{icons,mendeleydesktop}
+    cp -R share/icons ${pkgdir}/usr/share
+    cp -R share/mendeleydesktop ${pkgdir}/usr/share
+
+    #Remove bundled Qt from package
+    cat << __EOF__
+Removing bundled Qt library.
+If you used "--force-bundled-qt" to start mendeley,
+make sure you remove any old versions of ".desktop" file of mendeley in ~/.local/share/applications/,
+because mendeley will automatically create one there. This will apply only to version 1.13.6 or older.
+__EOF__
 }
