virtualbox: replace kernel26-headers with linux-headers

diff --git a/virtualbox/PKGBUILD b/virtualbox/PKGBUILD
--- a/virtualbox/PKGBUILD
+++ b/virtualbox/PKGBUILD
@@ -1,21 +1,22 @@
+# Maintainer: Sebastien Luttringer <seblu+arch@seblu.net>
 #
 # Chakra Packages for Chakra, part of chakra-project.org
 #
 # maintainer (i686): Phil Miller <philm[at]chakra-project[dog]org>
 # maintainer (x86_64): Manuel Tortosa <manutortosa[at]chakra-project[dot]org>
 
-# include global config
-
 pkgname=virtualbox
-pkgver=4.0.6
-_build=71344
-pkgrel=1
+pkgver=4.1.2
+_build=73507
+pkgrel=2
 pkgdesc='Oracle VM VirtualBox Binary Edition'
 arch=('i686' 'x86_64')
-url='http://virtualbox.org'
+url='http://virtualbox.org/'
 license=('GPL2')
-depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'gcc' 'make' 'kernel26-headers' 'python2')
+depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'linux-headers' 'python2')
+options=('!strip')
 optdepends=('virtualbox-ext-oracle: for Oracle extensions'
+            'dkms: for handling kernel modules with dkms'
             'qt: for GUI support'
             'sdl: for VBoxSDL and GUI support'
             'mesa: for OpenGL support'
@@ -25,100 +26,134 @@ optdepends=('virtualbox-ext-oracle: for Oracle extensions'
             'pulseaudio: for PulseAudio support')
 provides=("virtualbox=${pkgver}")
 conflicts=('virtualbox' 'virtualbox-ose' 'virtualbox-modules')
-backup=('etc/vbox/vbox.cfg')
-install='virtualbox.install'
+backup=('etc/vbox/vbox.cfg' 'etc/conf.d/vboxdrv' 'etc/conf.d/vboxweb')
+install='install'
+
 _sarch='x86'
 [ "${CARCH}" = 'x86_64' ] && _sarch='amd64'
 
-source=("VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run::http://download.virtualbox.org/virtualbox/${pkgver}/VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run"
-        '10-vboxdrv.rules'
-        'vboxdrv')
-md5sums=('45414b45e5b43e95068b1f3fec71de76'
-         '98859bfca9ef2ebf2ea43eb9123316fc'
-         '8b3b5fb34d5e8594ee873d7947f3d09b')
+source=(
+  "VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run::http://download.virtualbox.org/virtualbox/${pkgver}/VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run"
+  '10-vboxdrv.rules'
+  'vboxdrv.rc'
+  'vboxdrv.conf'
+  'vboxweb.rc'
+  'vboxweb.conf'
+)
+sha256sums=('bbf488cda504f05e2f21acf726c058db7844993c8b41012dc1a092eaac35b50a'
+            '69417a9e8855cab8e4878886abe138f559fd17ae487d4cd19c8a24974a8bbec2'
+            '578b63ab173cdcd9169d8aff00caf48668e46a6886bb90fd34a0fbe63e180a4e'
+            'a3961bdeac733264320ec3b7de49018cbdb7e26b726170370feac8b809bf0bdd'
+            '656905de981ffa24f6f921c920538854a235225053f44baedacc07b46ca0cf56'
+            '12dbba3b59991f2b68cddeeeda20236aeff63e11b7e2d1b08d9d6a82225f6651')
+[ "${CARCH}" = i686 ] && sha256sums[0]='f98dad52d5f1e29f75b4195a6b65af8e82f65785e0a841e4416dcf2134bbb807'
+_installdir='/opt/VirtualBox'
 
-[ "${CARCH}" = 'x86_64' ] && md5sums[0]='133cfbb8dc11da780b24f1ef5ef06697'
-
-build() {
+package() {
   # Check and unpack the run package via sh(1)
   sh "VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run" --check
   echo yes | sh "VirtualBox-${pkgver}-${_build}-Linux_${_sarch}.run" --target "${srcdir}" \
     --nox11 --noexec &> /dev/null
 
   # Unpack bundled files
-  install -d "${pkgdir}/opt/VirtualBox"
-  cd "${pkgdir}/opt/VirtualBox"
+  install -d "${pkgdir}/${_installdir}"
+  cd "${pkgdir}/${_installdir}"
   tar -xjf "${srcdir}/VirtualBox.tar.bz2"
 
   # Hardened build: Mark binaries suid root, create symlinks for working around
   #                 unsupported $ORIGIN/.. in VBoxC.so and make sure the
   #                 directory is only writable by the user (paranoid).
-  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP}
+  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP,NetAdpCtl}
   for _lib in VBox{VMM,REM,RT,DDU,XPCOM}.so; do
-    ln -sf "/opt/VirtualBox/${_lib}" "components/${_lib}"
+    ln -sf "${_installdir}/${_lib}" "components/${_lib}"
   done
   chmod go-w .
 
-  # VBoxNetAdpCtl needs to be suid root in any case
-  chmod 4511 VBoxNetAdpCtl
-
   # Replace VirtualBox built-in Qt by system Qt libraries (disabled as of
   # 2010-03-26, 3.1.6-1)
-  for _lib in libQt{Core,Gui,Network,OpenGL}; do
-    rm "${_lib}VBox.so.4"
-    ln -s "/usr/lib/${_lib}.so.4" "${_lib}VBox.so.4"
-  done
+  #for _lib in libQt{Core,Gui,Network,OpenGL}; do
+  #  rm "${_lib}VBox.so.4"
+  #  ln -s "/usr/lib/${_lib}.so.4" "${_lib}VBox.so.4"
+  #done
 
   # Patch "vboxshell.py" to use Python 2.x instead of Python 3
-  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/opt/VirtualBox/vboxshell.py"
+  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/${_installdir}/vboxshell.py"
 
-  # Install the SDK
-  cd "${pkgdir}/opt/VirtualBox/sdk/installer"
-  VBOX_INSTALL_PATH="/opt/VirtualBox" python2 vboxapisetup.py install --root "${pkgdir}"
-  rm -Rf build
-  cd "${pkgdir}/opt/VirtualBox"
-
-  # Install rc.d script for module compilation
-  install -Dm0755 "${srcdir}/vboxdrv" "${pkgdir}/etc/rc.d/vboxdrv"
-
-  # Replace init script stuff
+  # Update new initscripts way of life in VBox.sh
   sed -i -e 's,sudo /etc/init.d/vboxdrv setup,/etc/rc.d/vboxdrv setup,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
-  sed -i -e 's,sudo /etc/init.d/vboxdrv restart,modprobe vboxdrv,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
+    "${pkgdir}/${_installdir}/VBox.sh"
+  sed -i -e 's,sudo /etc/init.d/vboxdrv restart,/etc/rc.d/vboxdrv restart,g' \
+    "${pkgdir}/${_installdir}/VBox.sh"
+
+  # Install vboxdrv initscript
+  install -D -m 0755 "${srcdir}/vboxdrv.rc" "${pkgdir}/etc/rc.d/vboxdrv"
+  install -D -m 0644 "${srcdir}/vboxdrv.conf" "${pkgdir}/etc/conf.d/vboxdrv"
+  
+  # Install vboxweb initscript
+  install -D -m 0755 "${srcdir}/vboxweb.rc" "${pkgdir}/etc/rc.d/vboxweb"
+  install -D -m 0644 "${srcdir}/vboxweb.conf" "${pkgdir}/etc/conf.d/vboxweb"
 
   # Install udev rules
-  install -Dm0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  install -D -m 0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  ln -s "${_installdir}/VBoxCreateUSBNode.sh" "${pkgdir}/lib/udev/VBoxCreateUSBNode.sh"
 
-  # Symlink the launchers
-  install -d "${pkgdir}/usr/bin"
+  # Install the SDK
+  cd "${pkgdir}/${_installdir}/sdk/installer"
+  VBOX_INSTALL_PATH="${_installdir}" python2 vboxapisetup.py install --root "${pkgdir}"
+  rm -r -f build
+  cd "${pkgdir}/${_installdir}"
+
+  # Symlink the launchers. Second link can fail if fs is not case sensitive.
+  install -d -m 0755 "${pkgdir}/usr/bin"
   for _bin in VirtualBox VBox{Headless,Manage,SDL,SVC,Tunctl,NetAdpCtl} rdesktop-vrdp; do
-    ln -s "/opt/VirtualBox/${_bin}" "${pkgdir}/usr/bin/${_bin}"
+    ln -s "${_installdir}/${_bin}" "${pkgdir}/usr/bin/${_bin}"
+    ln -s "${_installdir}/${_bin}" "${pkgdir}/usr/bin/${_bin,,}" &>/dev/null || :
   done
 
   # Symlink the desktop icon and ".desktop" files
-  install -d "${pkgdir}/usr/"{share/applications,share/pixmaps}
-  ln -s "/opt/VirtualBox/VBox.png" "${pkgdir}/usr/share/pixmaps/VBox.png"
-  ln -s "/opt/VirtualBox/virtualbox.desktop" "${pkgdir}/usr/share/applications/VirtualBox.desktop"
+  install -d -m 0755 "${pkgdir}/usr/"{share/applications,share/pixmaps}
+  ln -s "${_installdir}/VBox.png" "${pkgdir}/usr/share/pixmaps/VBox.png"
+  ln -s "${_installdir}/icons/128x128/virtualbox.png" "${pkgdir}/usr/share/pixmaps/virtualbox.png"
+  ln -s "${_installdir}/virtualbox.desktop" "${pkgdir}/usr/share/applications/virtualbox.desktop"
 
   # Symlink mime info
-  install -d "${pkgdir}/usr/share/mime/packages"
-  ln -s "/opt/VirtualBox/virtualbox.xml" "${pkgdir}/usr/share/mime/packages/virtualbox.xml"
+  install -d -m 0755 "${pkgdir}/usr/share/mime/packages"
+  ln -s "${_installdir}/virtualbox.xml" "${pkgdir}/usr/share/mime/packages/virtualbox.xml"
 
   # Symlink doc
-  install -d "${pkgdir}/usr/share/doc/${pkgname}"
-  ln -s "/opt/VirtualBox/VirtualBox.chm" "${pkgdir}/usr/share/doc/$pkgname/VirtualBox.chm"
+  install -d -m 0755 "${pkgdir}/usr/share/doc/${pkgname}"
+  ln -s "${_installdir}/VirtualBox.chm" "${pkgdir}/usr/share/doc/$pkgname/virtualbox.chm"
 
-  # Symlink the license
-  install -d "${pkgdir}/usr/share/licenses/${pkgname}"
-  ln -s /opt/VirtualBox/LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  # Symlink module sources
+  install -d -m 0755 "${pkgdir}/usr/src"
+  ln -s "${_installdir}/src/vboxhost" "${pkgdir}/usr/src/vboxhost-${pkgver}"
 
-  # Setup configuration
-  install -d "${pkgdir}/etc/vbox"
-  echo 'INSTALL_DIR="/opt/VirtualBox"' > "${pkgdir}/etc/vbox/vbox.cfg"
+  # Symlink icons
+  cd "${pkgdir}/${_installdir}/icons"
+  for _dir in *; do
+    cd "${_dir}"
+    install -d -m 0755 "${pkgdir}/usr/share/icons/hicolor/${_dir}/"{apps,mimetypes}
+    for _icon in *; do
+      if [[ "${_icon}" = 'virtualbox.png' ]]; then
+          ln -s "${_installdir}/icons/${_dir}/${_icon}" "${pkgdir}/usr/share/icons/hicolor/${_dir}/apps/${_icon}"
+      else
+          ln -s "${_installdir}/icons/${_dir}/${_icon}" "${pkgdir}/usr/share/icons/hicolor/${_dir}/mimetypes/${_icon}"
+      fi
+    done
+    cd - >/dev/null
+  done
+
+  # Write the configuration file 
+  install -d -m 0755 "${pkgdir}/etc/vbox"
+  echo "# VirtualBox installation directory" > "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_DIR='${_installdir}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "# VirtualBox version" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_VER='${pkgver}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_REV='${_build}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  chmod 0644 "${pkgdir}/etc/vbox/vbox.cfg"
   
   # Create the directory below if it doesn't exist
-  install -d "${pkgdir}/var/run/VirtualBox"
+  install -d -m 0755 "${pkgdir}/var/run/VirtualBox"
 }
 
 # vim:set ts=2 sw=2 ft=sh et:
